# site settings
title: Next Gen Hardware
subtitle: Ball-Bot Project
email: kammorne@gmail.com
description: A portfolio displaying the work done towards a prototype self-balancing ball-bot
baseurl: "/lagoma1_IN722" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Michael Lagocki
street_address:
city: Dunedin
state:
zip_code:
country: New Zealand
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/kammorne
gitlab_url: https://gitlab.op-bit.nz/LAGOMA1
googleplus_url:
instagram_url: https://instagram.com
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
